kind: pipeline
type: docker
name: run_tests

clone:
  depth: 50
  tags: true
  skip_verify: true
  commands:
    - echo

steps:
- name: flake8
  image: real_env
  pull: never
  commands:
    - flake8 --config .tox.ini ./josiann

- name: mypy
  image: real_env
  pull: never
  failure: ignore
  commands:
    - mypy --config-file .mypy.ini ./josiann

- name: pytest
  image: real_env
  pull: never
  commands:
    - python -m pytest -v ./tests/test_sa.py
