fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--exclude, vulture_whitelist.py]
      - id: ruff-format
        args: [--exclude, vulture_whitelist.py]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
        types: [python]
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: (^tests/)|(^docs/)|(^build/)|(vulture_whitelist.py)
        args: [--strict, "josiann"]
        pass_filenames: false
        additional_dependencies:
          - "numpy"
          - "attrs"
          - "types-attrs"
          - "types-tqdm"
        language_version: python3.10
