fail_fast: false

repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.9
        exclude: ^build/

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
        types: [python]
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.8
    hooks:
      - id: pylint
        args: [--disable=all, --enable=unused-import]
        language_version: python3.9

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        exclude: (^tests/)|(^doc/)|(^build/)|(vulture_whitelist.py)
        args: [--strict]
        additional_dependencies:
          - "numpy==1.24"
          - "attrs==22.2.0"
          - "types-attrs==19.1.0"
        language_version: python3.9
